<!DOCTYPE html>
<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="{{ current_lang.lang }}"><![endif]-->
<!--[if IE 7]><html class="no-js lt-ie9 lt-ie8" lang="{{ current_lang.lang }}"><![endif]-->
<!--[if IE 8]><html class="no-js lt-ie9" lang="{{ current_lang.lang }}"><![endif]-->
<!--[if IE 9 ]><html class="no-js ie9"><![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--><html class="no-js"><!--<![endif]-->
<head>
	 <meta charset="utf-8">
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1">

    <title>{{ page_title }}</title>
    <meta name="description" content="{{ page_description }}">

   {% if settings.fb_admins %}
        {# FB user ids that can moderate the FB comments generated by the plugin. To find your ids go to: http://findmyfbid.com/ #}
        <meta property="fb:admins" content="{{ settings.fb_admins }}">
    {% endif %}
    {% if store_fb_app_id %}
        <meta property="fb:app_id" content="{{ store_fb_app_id }}">
    {% elseif not store.has_custom_domain %}
        <meta property="fb:app_id" content="{{ fb_app.id }}">
    {% endif %}

    {# OG tags to control how the page appears when shared on Facebook. See http://ogp.me/ #}
    {% snipplet "metas/facebook-og.tpl" %}
    {# Twitter tags to control how the page appears when shared on Twitter. See https://dev.twitter.com/cards/markup #}
    {% if template == 'product' %}
        {# Twitter #}
        {% snipplet "metas/twitter-product.tpl" %}
        {# Facebook #}
        {% snipplet "metas/facebook-product-og.tpl" %}
    {% endif %}

    {# Bootsrap included for the modal #}
    {{ '//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css' | css_tag }}
    {{ 'js/bxslider/jquery.bxslider.css' | static_url | css_tag }}

    {{ '//maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css' | css_tag }}
    {{ '//fonts.googleapis.com/icon?family=Material+Icons' | css_tag }}
    {{ '//fonts.googleapis.com/css?family=Lato:700,900,400italic,700italic|Slabo+27px|Oswald:400,300,700|Istok+Web:400,700,400italic,700italic|Arvo:400,700,400italic,700italic|Montserrat:400,700|Open+Sans+Condensed:300,300italic,700|Open+Sans:400,300,700|Lora:400,700|Roboto+Condensed:400italic,700italic,300,400,700|Droid+Sans:400,700' | css_tag }}
    
    {# Theme's CSS #}
    {{ 'css/custom-styles.scss.tpl' | static_url | css_tag }}
    {{ 'css/style.css' | static_url | css_tag }}

    {# Themes include jquery 1.5 by default. With this setting we can include our own jQuery #}
    {% set nojquery = true %}
    {{ '//ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js' | script_tag }}
    {% if params.preview %}
        {{ 'js/instatheme.js' | static_url | script_tag }}
    {% endif %}
    <script>jQuery('html').removeClass('no-js').addClass('js');</script>

    {% head_content %}

    {# Merchant's custom CSS #}
    <style>
        {{ settings.css_code }}
    </style>
</head>
{# itemscope and itemtype are used for htto://schema.org format #}
<body itemscope itemtype="http://schema.org/WebPage" itemid="body" class="{% if customer %}customer-logged-in{% endif %} template-{{ template | replace('.', '-') }}">

{# Only remove this if you want to take away the theme onboarding advices #}
{% set show_help = not has_products %}

 {# Includes all social JS. Don't worry they are async #}
    {{ social_js }}
    {# Includes a fixed bar that let logged in merchants go back to their admin panel #}
    {{back_to_admin}}
    {#  Mobile Nav - uses Pushy Plugin, included on skeleton.js and the CSS inside js folder (you need to link it if you want to use it)  #}
    <nav class="pushy pushy-left">
        <div class="mobile-logo pull-left">
            <div class="container">
                <span class="menu-btn btn btn-default btn-close pull-right m-top"><i class="material-icons">&#xE5CD;</i></span>
            </div>
            <div class="container logo-container m-top m-bottom">
                {% if has_logo %}
                    {{ store.logo  | img_tag(store.name,  {class: 'img-responsive m-auto'}) | a_tag(store.url, '', 'mobile-logo') }}
                {% else %}
                    <a class="no-logo" class="text-wrap pull-left m-none p-none d-block" href="{{ store.url }}">{{ store.name }}</a>
                {% endif %}
            </div>
            <div class="container lang-wrapper">
                <div class="search-lang-wrapper">
                    {% if languages | length > 1 %}
                        <div class="languages">
                            <ul class="language list-style-none p-none">
                                {% for language in languages %}
                                    <li class="d-inline-block">
                                        <a href="{{ language.url }}">
                                            {{ language.country | flag_url | img_tag(language.name) }}
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <ul id="mobile-navigation" class="list-style-none p-none container-fluid clear-both">
            {% if not customer %}
                {% if store.customer_accounts != 'mandatory' %}
                    <li>{{ "Crear cuenta" | translate | a_tag(store.customer_register_url, '', 'd-block container text-decoration-none text-wrap no-link p-top p-bottom') }}</li>
                {% endif %}
                    <li class="border-bottom">{{ "Iniciar sesión" | translate | a_tag(store.customer_login_url, '', 'd-block container text-decoration-none text-wrap no-link p-top p-bottom') }}</li>
            {% else %}
                <li>{{ "Mi cuenta" | translate | a_tag(store.customer_home_url, '', 'd-block container text-decoration-none text-wrap no-link p-top p-bottom') }}</li>
                <li class="border-bottom">{{ "Cerrar sesión" | translate | a_tag(store.customer_logout_url, '', 'd-block container text-decoration-none text-wrap no-link p-top p-bottom') }}</li>
            {% endif %}
            {% snipplet "navigation/navigation-mobile.tpl" %}
            <li>
                <a class="d-block container text-decoration-none text-wrap no-link p-top p-bottom border-bottom" href="{{ store.contact_url }}">
                    {{ 'Contacto' | translate }}</a>
            </li>
        </ul>
    </nav>
    <div class="site-overlay"></div>
    {#  **** Store Main Container ****  #}
        {% snipplet "navigation/header-nav.tpl" %}
        {# template_content renders the template file #}
        <div id="main-content" class="{% if template == 'product' %}no-margin{% endif %} {% if store.has_accounts or languages | length > 1 %} with-top-bar{% endif %}">
            {% template_content %}
        {% if not has_products %}
        {# This is a snipplet to show the user the payment and send methods the first time they visit the store #}
           {% snipplet "defaults/show_help_footer.tpl" %}
        {% else %}
            {% snipplet "footer.tpl" %}
        {% endif %}
        </div>

        {# Our themes do not support IE versions lower than IE8 #}
        <!--[if lt IE 8]>
        <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->
{# Bootsrap included for the modal #}
{{ '//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js' | script_tag }}
{# Though all third party JS are included on the theme, we put them all together in a single file to reduce requests #}
{{ 'js/external.js' | static_url | script_tag }}
{# Including it as a template instead of a static .js.tpl file because it uses the template variable that would cause some nasty bugs when the JS is cached #}
<script>
    {% snipplet "js/store.js.tpl"  %}
</script>
{# Olark Chat JS #}
{% if store.live_chat %}
    {% snipplet "js/olark.js.tpl"  %}
{% endif %}
{# Custom JS added by merchant #}
{{ store.assorted_js | raw }}
</body>
</html>
