<!DOCTYPE html>
<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="{{ current_lang.lang }}"><![endif]-->
<!--[if IE 7]><html class="no-js lt-ie9 lt-ie8" lang="{{ current_lang.lang }}"><![endif]-->
<!--[if IE 8]><html class="no-js lt-ie9" lang="{{ current_lang.lang }}"><![endif]-->
<!--[if IE 9 ]><html class="no-js ie9"><![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--><html class="no-js"><!--<![endif]-->
<head>
     <meta charset="utf-8">
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1">

    <title>{{ page_title }}</title>
    <meta name="description" content="{{ page_description }}">

   {% if settings.fb_admins %}
        {# FB user ids that can moderate the FB comments generated by the plugin. To find your ids go to: http://findmyfbid.com/ #}
        <meta property="fb:admins" content="{{ settings.fb_admins }}">
    {% endif %}
    {% if store_fb_app_id %}
        <meta property="fb:app_id" content="{{ store_fb_app_id }}">
    {% elseif not store.has_custom_domain %}
        <meta property="fb:app_id" content="{{ fb_app.id }}">
    {% endif %}

    {# OG tags to control how the page appears when shared on Facebook. See http://ogp.me/ #}
    {% snipplet "metas/facebook-og.tpl" %}
    {# Twitter tags to control how the page appears when shared on Twitter. See https://dev.twitter.com/cards/markup #}

    {# Bootsrap included for the modal #}
    {{ '//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css' | css_tag }}

    {{ '//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css' | css_tag }}
    {{ '//fonts.googleapis.com/icon?family=Material+Icons' | css_tag }}
    {{ '//fonts.googleapis.com/css?family=Open+Sans+Condensed:300,300italic,700|Open+Sans:400,300,700|Slabo+27px|Oswald:400,300,700|Lora:400,700|Roboto+Condensed:400italic,700italic,300,400,700|Droid+Sans:400,700' | css_tag }}
    
    {# Theme's CSS #}
    {{ 'css/style.css' | static_url | css_tag }}
    {{ 'css/custom-styles.scss.tpl' | static_url | css_tag }}

    {# Themes include jquery 1.5 by default. With this setting we can include our own jQuery #}
    {% set nojquery = true %}
    {{ '//ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js' | script_tag }}
    {% if params.preview %}
        {{ 'js/instatheme.js' | static_url | script_tag }}
    {% endif %}
    <script>jQuery('html').removeClass('no-js').addClass('js');</script>

    {# Merchant's custom CSS #}
    <style>
        {{ settings.css_code }}
    </style>
</head>
<body itemscope itemtype="http://schema.org/WebPage" itemid="body" class="template-{{ template }}">
{{ social_js }}
{{back_to_admin}}
<div id="password-page">
    <header class="password-logo-container container">
        <div class="row">
            <div class="logo-container text-center m-top m-double-bottom col-xs-12 col-sm-12 col-md-12 col-lg-12">
                {% if has_logo %}
                    <h1 class="img logo m-none m-none-top">
                       {{ store.logo  | img_tag(store.name,  {class: 'img-responsive img-responsive col-xs-8 col-xs-offset-2 col-sm-8 col-md-4 col-md-offset-4 col-lg-4 col-lg-offset-4'}) | a_tag(store.url) }}
                    </h1>
                    <div id="no-logo-wrapper" class="hidden">
                        <div id="logo">
                            <a id="no-logo" href="{{ store.url }}">{{ store.name }}</a>
                        </div>
                    </div>
                {% else %}
                    <div class="img logo hidden">
                        {{ store.logo  | img_tag(store.name,  {class: 'img-responsive col-xs-8 col-xs-offset-2 col-sm-8 col-md-8 col-lg-8'}) | a_tag(store.url)}}
                    </div>
                    <h1 id="no-logo-wrapper" class="m-none-top">
                        <div id="logo">
                            <a id="no-logo" href="{{ store.url }}">{{ store.name }}</a>
                        </div>
                    </h1>
                {% endif %}
            </div>
        </div>
    </header>
    <div class="password-icon container text-center m-bottom">
        {{ "images/construction-icon.svg" | static_url | img_tag("",  {class: 'img-responsive col-xs-4 col-xs-offset-4 col-sm-6 col-sm-offset-3 col-md-2 col-md-offset-5 col-lg-2 col-lg-offset-5'}) }} 
    </div>
    <div class="password-message container text-center">
        <h2>{{ message }}</h2>
    </div>
    {% if store.facebook or store.twitter or store.google_plus or store.pinterest or store.instagram %}
        <div class="password-social-networks-container container text-center">
           <ul class="social-networks list-style-none p-none m-left-none m-half-top">
        {% for sn in ['facebook', 'twitter', 'google_plus', 'pinterest', 'instagram'] %}
            {% set sn_url = attribute(store,sn) %}
            {% if sn_url %}
                <li class="{{ sn }} m-half-bottom d-inline-block m-half-right">
                    <a target="_blank" href="{{ sn_url }}" class="no-link btn-circle pull-left">
                        <i class="fa fa-{{ sn == 'google_plus' ? 'google-plus' : sn }} d-block"></i>
                    </a>
                </li>
            {% endif %}
        {% endfor %}
        </ul>
        </div>
    {% endif %}
    </div>
    <footer>
        <div id="footer-common" class="container p-half-top text-center-xs">
            <form method="post" class="row m-double-top">
                <div class="form-group col-xs-12 col-xs-offset-0 col-sm-4 col-sm-offset-4 col-md-4 col-md-offset-4 col-lg-4 col-lg-offset-4">
                    <input type="password" name="password" placeholder="{{ 'Contraseña de acceso' | translate }}" class="form-control m-half-bottom  {% if invalid_password == true %}input-error{% endif %}">
                     {% if invalid_password == true %}
                        <div class="alert alert-danger text-center-xs"><div class="arrow arrow-up"></div><i class="material-icons d-inline pull-left m-half-right m-none-xs m-half-bottom-xs">&#xE000;</i><p>{{ 'La contraseña es incorrecta.' | translate }}</p></div>
                    {% endif %}
                    <input type="submit" name="unlock" class="btn btn-primary col-xs-12 col-sm-12 col-md-12 col-lg-12" value='{{ "Desbloquear" | translate }}'>
                </div>
            </form>
            {% if store.phone or store.address or store.blog %}
                <ul class="store-contact-container list-style-none p-none m-none text-center">
                    {% if store.phone %}
                        <li>{{ store.phone }}</li>
                    {% endif %}
                    {% if store.address %}
                        <li>{{ store.address }}</li>
                    {% endif %}
                    {% if store.blog %}
                        <li class="blog"><a target="_blank" href="{{ store.blog }}">{{ store.blog }}</a></li>
                    {% endif %}
                    {% if store.email %}
                        <li class="email">{{ store.email | mailto }}</li>
                    {% endif %}
                </ul>
            {% endif %}
        </div>
        <div id="footer-legal">
                <div class="powered-by text-center m-double-top">
                    {#
                    La leyenda que aparece debajo de esta linea de código debe mantenerse
                    con las mismas palabras y con su apropiado link a Tienda Nube;
                    como especifican nuestros términos de uso: http://www.tiendanube.com/terminos-de-uso .
                    Si quieres puedes modificar el estilo y posición de la leyenda para que se adapte a
                    tu sitio. Pero debe mantenerse visible para los visitantes y con el link funcional.
                    Os créditos que aparece debaixo da linha de código deverá ser mantida com as mesmas
                    palavras e com seu link para Nuvem Shop; como especificam nossos Termos de Uso:
                    http://www.nuvemshop.com.br/termos-de-uso. Se você quiser poderá alterar o estilo
                    e a posição dos créditos para que ele se adque ao seu site. Porém você precisa
                    manter visivél e com um link funcionando.
                    #}
                    {{ powered_by_link }}
                </div>
            <div class="copyright-container text-center m-bottom">
                {{ "Copyright {1} - {2}. Todos los derechos reservados." | translate( (store.business_name ? store.business_name : store.name) ~ (store.business_id ? ' - ' ~ store.business_id : ''), "now" | date('Y') ) }}
            </div>
        </div>
    </footer>
</div>
</body>
</html>